[[apps]]
name = "style"
path = "FLASH0:hello_flasher.elf"
restart_on_failure = false
stack_size = 8192
args = []

[[apps]]
name = "style"
path = "FLASH0:hello.elf"
restart_on_failure = false
stack_size = 8192
args = []

