[[apps]]
name = "OTA"
path = "APPS:[why2025_ota]why2025_ota.elf"
restart_on_failure = false
start_delay = 30
start_every = 60
stack_size = 8192
args = ["--debug"]

[[apps]]
name = "sponsors"
path = "APPS:[why2025_sponsors]why2025_sponsors.elf"
restart_on_failure = false
stack_size = 16384
args = ["--boot"]
